### PR TITLE
Updated passing https settings to request wrapper

### PR DESCRIPTION
**Pull request by unauthorized-401**
Proposed solution for fixing https api issue (please check my comment titled "Https" on Chrome Web Store in Problems section)
https://chrome.google.com/webstore/detail/feedly-notifier/egikgfbhipinieabdmcpigejkaomgjgb/support?utm_source=chrome-ntp-icon

### CODE REVIEW

**Comment by olsh** [comment]
Thank you for the PR. 👍 
Well, actually it's not an issue, Feedly team recommended to use HTTPS only for Auth flow. But personally, I agree that we should use HTTPS for all requests.

**Comment by unauthorized-401** [comment]
I would say I have more less special case. My https traffic is not proxied while http traffic is proxied via Tor. As Tor is a loaded network I actually get captcha in response of http Feedly api requests but do not have an ability to answer it and even know about it (extension does not track this thing and does not notify me). Switching everything to https will fix my issue but it makes sense to check captcha in api response and to show it to the end user of the extension anyway.

**Comment by olsh** [comment]
Which service sends the captcha?

**Comment by unauthorized-401** [comment]
403 + captcha in response body here:
http://cloud.feedly.com/v3/streams/user...
http://cloud.feedly.com/v3/markers/counts?...
and other requests to the same domain by http. Everything works fine though when I turn off Tor proxy for http requests.

**Comment by olsh** [comment]
So, I suppose the captcha comes from third party reverse proxy server like cloudflare? 
If it is the case, I think that showing the captcha to end user is not in responsibility of the extension.

**Comment by unauthorized-401** [comment]
The captcha is shown by the Feedly api I am not sure if they use Cloudflare or something. Probably they show it because of lot of Tor requests. My concern is that for now the captcha is thrown at user and just suppressed by the extension without notifying that user has to do something. It makes sense not to suppress the captcha but to handle and show it or whatever Feedly api gives back to the extension. I'll check and prepare a separate PR probably for this thing.

**Comment by olsh** [comment]
The captcha is not documented here: https://developer.feedly.com/
Therefore I don't think that we should implement this feature.

**Comment by unauthorized-401** [comment]
You're right, I'll discuss with Feedly developers first maybe this is just a temporary feature or it will be removed soon (or documented).

**Comment by olsh** [comment]
Thanks!

**Pull request merged**
